//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::ErpConnectionAuthStatus;
use super::sea_orm_active_enums::ErpConnectionStatus;
use super::sea_orm_active_enums::ErpEnvironment;
use super::sea_orm_active_enums::ErpProvider;
use super::sea_orm_active_enums::ErpProviderAuthType;
use super::sea_orm_active_enums::ErpProviderType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "connection_identity")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub uuid: Uuid,
    pub tenant_id: i64,
    pub erp_provider: ErpProvider,
    pub erp_type: ErpProviderType,
    pub erp_auth_type: ErpProviderAuthType,
    #[sea_orm(column_type = "Text", nullable)]
    pub display_name: Option<String>,
    pub environment: ErpEnvironment,
    pub status: ErpConnectionStatus,
    pub auth_status: ErpConnectionAuthStatus,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub is_enabled: bool,
    pub last_success_at: Option<DateTimeWithTimeZone>,
    pub last_error_code: Option<String>,
    pub last_error_message: Option<String>,
    pub error_at: Option<DateTimeWithTimeZone>,
    pub sync_enabled_push: bool,
    pub sync_enabled_pull: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub secret_storage_ref: Option<String>,
    pub secret_version: Option<String>,
    pub scopes: Option<Vec<String>>,
    pub provider_realm_id: Option<String>,
    pub provider_tenant_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub company_file_identity: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub company_file_path: Option<String>,
    pub company_file_id: Option<String>,
    pub system_version: Option<String>,
    pub web_connector_app_name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::connection_run::Entity")]
    ConnectionRun,
    #[sea_orm(has_one = "super::erp_connection_credentials::Entity")]
    ErpConnectionCredentials,
    #[sea_orm(has_one = "super::erp_connection_sync_state::Entity")]
    ErpConnectionSyncState,
    #[sea_orm(
        belongs_to = "super::tenant::Entity",
        from = "Column::TenantId",
        to = "super::tenant::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Tenant,
}

impl Related<super::connection_run::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ConnectionRun.def()
    }
}

impl Related<super::erp_connection_credentials::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ErpConnectionCredentials.def()
    }
}

impl Related<super::erp_connection_sync_state::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ErpConnectionSyncState.def()
    }
}

impl Related<super::tenant::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tenant.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
