//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::ErpConnectionAuthTokenType;
use super::sea_orm_active_enums::ErpConnectionReauthReason;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "erp_connection_credentials")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub uuid: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(unique)]
    pub connection_id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub client_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub issuer_base_url: Option<String>,
    pub token_type: ErpConnectionAuthTokenType,
    pub reauth_required_reason: Option<ErpConnectionReauthReason>,
    #[sea_orm(column_type = "Text", nullable)]
    pub reauth_url: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub enc_scheme: String,
    #[sea_orm(column_type = "Text")]
    pub enc_key_id: String,
    pub enc_version: i32,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub enc_iv: Option<Vec<u8>>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub enc_tag: Option<Vec<u8>>,
    #[sea_orm(column_type = "Text", nullable)]
    pub access_token: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub refresh_token: Option<String>,
    pub access_token_expires_at: Option<DateTimeWithTimeZone>,
    pub refresh_token_expires_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub id_token_enc: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub provider_user_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub provider_password: Option<String>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub client_cert: Option<Vec<u8>>,
    #[sea_orm(column_type = "Text", nullable)]
    pub private_key: Option<String>,
    pub cert_expires_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub session_token: Option<String>,
    pub session_expires_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub api_access_token: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub api_access_token_key: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::connection_identity::Entity",
        from = "Column::ConnectionId",
        to = "super::connection_identity::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ConnectionIdentity,
}

impl Related<super::connection_identity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ConnectionIdentity.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
