//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::ConnectionRunStatus;
use super::sea_orm_active_enums::ConnectionRunType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "connection_run")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub uuid: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub status: ConnectionRunStatus,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
    pub run_type: ConnectionRunType,
    pub connection_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::connection_identity::Entity",
        from = "Column::ConnectionId",
        to = "super::connection_identity::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ConnectionIdentity,
    #[sea_orm(has_many = "super::sync_event::Entity")]
    SyncEvent,
}

impl Related<super::connection_identity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ConnectionIdentity.def()
    }
}

impl Related<super::sync_event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SyncEvent.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
