//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "erp_connection_sync_state")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub uuid: Uuid,
    #[sea_orm(unique)]
    pub connection_id: i64,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub sync_cursor: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub sync_lock_owner: Option<String>,
    pub sync_lock_until: Option<DateTimeWithTimeZone>,
    pub rate_limit_remaining: Option<i32>,
    pub rate_limit: Option<i32>,
    pub rate_limit_reset_at: Option<DateTimeWithTimeZone>,
    pub rate_limit_backoff_until: Option<DateTimeWithTimeZone>,
    pub rate_limit_window_seconds: Option<i32>,
    pub updated_at: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::connection_identity::Entity",
        from = "Column::ConnectionId",
        to = "super::connection_identity::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ConnectionIdentity,
    #[sea_orm(has_many = "super::sync_event::Entity")]
    SyncEvent,
}

impl Related<super::connection_identity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ConnectionIdentity.def()
    }
}

impl Related<super::sync_event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SyncEvent.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
