//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::allowed_ip_address::Entity as AllowedIpAddress;
pub use super::api_token::Entity as ApiToken;
pub use super::connection_identity::Entity as ConnectionIdentity;
pub use super::erp_connection_sync_state::Entity as ErpConnectionSyncState;
pub use super::tenant::Entity as Tenant;
