//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "allowed_ip_address_status_enum"
)]
pub enum AllowedIpAddressStatusEnum {
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "inactive")]
    Inactive,
    #[sea_orm(string_value = "banned")]
    Banned,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "api_token_status_enum"
)]
pub enum ApiTokenStatusEnum {
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "inactive")]
    Inactive,
    #[sea_orm(string_value = "banned")]
    Banned,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "connection_run_status"
)]
pub enum ConnectionRunStatus {
    #[sea_orm(string_value = "success")]
    Success,
    #[sea_orm(string_value = "error")]
    Error,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "connection_run_type"
)]
pub enum ConnectionRunType {
    #[sea_orm(string_value = "poll")]
    Poll,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "currency")]
pub enum Currency {
    #[sea_orm(string_value = "usd")]
    Usd,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "enum")]
pub enum Enum {
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "removed")]
    Removed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "erp_connection_auth_status"
)]
pub enum ErpConnectionAuthStatus {
    #[sea_orm(string_value = "connected")]
    Connected,
    #[sea_orm(string_value = "needs_reauth")]
    NeedsReauth,
    #[sea_orm(string_value = "revoked")]
    Revoked,
    #[sea_orm(string_value = "error")]
    Error,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "erp_connection_auth_token_type"
)]
pub enum ErpConnectionAuthTokenType {
    #[sea_orm(string_value = "bearer")]
    Bearer,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "erp_connection_reauth_reason"
)]
pub enum ErpConnectionReauthReason {
    #[sea_orm(string_value = "refresh_expired")]
    RefreshExpired,
    #[sea_orm(string_value = "revoked")]
    Revoked,
    #[sea_orm(string_value = "invalid_grant")]
    InvalidGrant,
    #[sea_orm(string_value = "scopes_changed")]
    ScopesChanged,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "erp_connection_status"
)]
pub enum ErpConnectionStatus {
    #[sea_orm(string_value = "removed")]
    Removed,
    #[sea_orm(string_value = "active")]
    Active,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "erp_environment")]
pub enum ErpEnvironment {
    #[sea_orm(string_value = "production")]
    Production,
    #[sea_orm(string_value = "sandbox")]
    Sandbox,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "erp_provider")]
pub enum ErpProvider {
    #[sea_orm(string_value = "quickbooks")]
    Quickbooks,
    #[sea_orm(string_value = "dmsi")]
    Dmsi,
    #[sea_orm(string_value = "sap")]
    Sap,
    #[sea_orm(string_value = "salesforce")]
    Salesforce,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "erp_provider_auth_type"
)]
pub enum ErpProviderAuthType {
    #[sea_orm(string_value = "oauth")]
    Oauth,
    #[sea_orm(string_value = "oauth2")]
    Oauth2,
    #[sea_orm(string_value = "username_password")]
    UsernamePassword,
    #[sea_orm(string_value = "certificate")]
    Certificate,
    #[sea_orm(string_value = "api_token")]
    ApiToken,
    #[sea_orm(string_value = "session_token")]
    SessionToken,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "erp_provider_type")]
pub enum ErpProviderType {
    #[sea_orm(string_value = "desktop")]
    Desktop,
    #[sea_orm(string_value = "api")]
    Api,
    #[sea_orm(string_value = "edi")]
    Edi,
    #[sea_orm(string_value = "idoc")]
    Idoc,
    #[sea_orm(string_value = "webconnector")]
    Webconnector,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "sync_event_category"
)]
pub enum SyncEventCategory {
    #[sea_orm(string_value = "inventory")]
    Inventory,
    #[sea_orm(string_value = "order")]
    Order,
    #[sea_orm(string_value = "customer")]
    Customer,
    #[sea_orm(string_value = "other")]
    Other,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "sync_event_direction"
)]
pub enum SyncEventDirection {
    #[sea_orm(string_value = "push")]
    Push,
    #[sea_orm(string_value = "pull")]
    Pull,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "sync_event_method")]
pub enum SyncEventMethod {
    #[sea_orm(string_value = "list")]
    List,
    #[sea_orm(string_value = "get")]
    Get,
    #[sea_orm(string_value = "create")]
    Create,
    #[sea_orm(string_value = "update")]
    Update,
    #[sea_orm(string_value = "delete")]
    Delete,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "sync_event_status")]
pub enum SyncEventStatus {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "in_progress")]
    InProgress,
    #[sea_orm(string_value = "success")]
    Success,
    #[sea_orm(string_value = "error")]
    Error,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "system_id_key")]
pub enum SystemIdKey {
    #[sea_orm(string_value = "qbd")]
    Qbd,
    #[sea_orm(string_value = "qbo")]
    Qbo,
    #[sea_orm(string_value = "sapo")]
    Sapo,
}
