//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::SyncEventCategory;
use super::sea_orm_active_enums::SyncEventDirection;
use super::sea_orm_active_enums::SyncEventMethod;
use super::sea_orm_active_enums::SyncEventStatus;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "sync_event")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub uuid: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub original_record_body: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub details: Option<Json>,
    pub event_direction: SyncEventDirection,
    pub inventory_record_event_id: Option<i64>,
    pub sync_event_method: SyncEventMethod,
    pub sync_event_category: SyncEventCategory,
    pub attempts: i32,
    pub status: SyncEventStatus,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub last_error: Option<Json>,
    pub last_errored_date: Option<DateTimeWithTimeZone>,
    pub connection_sync_state_id: Option<i64>,
    pub connection_run_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::connection_run::Entity",
        from = "Column::ConnectionRunId",
        to = "super::connection_run::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    ConnectionRun,
    #[sea_orm(
        belongs_to = "super::erp_connection_sync_state::Entity",
        from = "Column::ConnectionSyncStateId",
        to = "super::erp_connection_sync_state::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    ErpConnectionSyncState,
    #[sea_orm(
        belongs_to = "super::inventory_record_event::Entity",
        from = "Column::InventoryRecordEventId",
        to = "super::inventory_record_event::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    InventoryRecordEvent,
}

impl Related<super::connection_run::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ConnectionRun.def()
    }
}

impl Related<super::erp_connection_sync_state::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ErpConnectionSyncState.def()
    }
}

impl Related<super::inventory_record_event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InventoryRecordEvent.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
